version: "2"

services:
  web:
    build: .
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  mongodb:
    image: "mongo"
    restart: always
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"